# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: sqlite3
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: heaven_dev

test:
  <<: *default
  database: heaven_test

production:
  <<: *default
  database: <%= ENV['HEAVEN_DB_NAME'] %>
  username: <%= ENV['HEAVEN_DB_USERNAME'] %>
  password: <%= ENV['HEAVEN_DB_PASSWORD'] %>
